# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto updating

on:
  push:
    branches: 
      - 'master'
env:
  PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
  HOSTNAME : ${{ secrets.SITE_HOST }}
  USER_NAME : ${{ secrets.SITE_USER }}

jobs:
  Pulish:
    name: Publish website
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure registry
        if: contains(github.event.head_commit.message, 'PUSH_IMAGE')
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push to Azure registry
        if: contains(github.event.head_commit.message, 'PUSH_IMAGE')
        run: |
          pwd
          ls
          # docker build -f  -t ${{ secrets.REGISTRY_SERVER }}/vickenradio:latest
          # docker push ${{ secrets.REGISTRY_SERVER }}/vickenradio:latest

      - uses: actions/checkout@v2 
      - name: pull latest on server
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "cd radioNode/ && git pull origin master -s recursive -X theirs && exit"
          
